### ISSUE TITLE
functools dependency?

### ISSUE THREAD

**Issue by colmoneill** [MaxNoe/python-gitpath#1]
Hi, thanks for the util!

When I try an run gitpath in my script I get an error:

```
from functools import lru_cache
ImportError: cannot import name lru_cache
```

So I tried a plain `import functools` but the error remains even if I `from functools import lru_cache`
I found similar issues here: http://stackoverflow.com/questions/17871784/installing-functools-gives-me-attributeerror-module-object-has-no-attribute-c#17872892

Any ideas what I am missing?

Thanks!

**Comment by maxnoe** [comment]
`lru_cache` is only available in Python 3. This module is thus python3 only.

**Comment by colmoneill** [comment]
Aha, this makes sense. Excuse my beginner knowledge. Thanks!
